pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "label=ready"
    actions:
      merge:
        method: squash
        strict: smart