FROM alpine:3.11
LABEL maintainer="sig-platform@spinnaker.io"
COPY orca-web/build/install/orca /opt/orca
RUN apk --no-cache add --update bash openjdk11-jre
RUN addgroup -S -g 10111 spinnaker
RUN adduser -S -G spinnaker -u 10111 spinnaker
RUN mkdir -p /opt/orca/plugins && chown -R spinnaker:nogroup /opt/orca/plugins
USER spinnaker
CMD ["/opt/orca/bin/orca"]
