FROM alpine:3.11
MAINTAINER sig-platform@spinnaker.io
COPY orca-web/build/install/orca /opt/orca
RUN apk --no-cache add --update bash openjdk8-jre
RUN adduser -D -S spinnaker
RUN mkdir -p /opt/spinnaker/plugins && chown -R spinnaker:nogroup /opt/spinnaker/plugins
USER spinnaker
CMD ["/opt/orca/bin/orca"]
