databaseChangeLog:
- changeSet:
    id: 20180905-add-application-status-build_time-index
    author: ajordens
    changes:
    - createIndex:
        indexName: orchestration_application_status_buildtime_idx
        tableName: orchestrations
        columns:
        - column:
            name: application
        - column:
            name: status
        - column:
            name: build_time
    rollback:
    - dropIndex:
        indexName: orchestration_application_status_buildtime_idx
        tableName: orchestrations
