package com.netflix.spinnaker.orca.api.pipeline.remote.messages;

import com.netflix.spinnaker.kork.annotations.Alpha;

/**
 * Remote stage message; all remote stage messages include the stageExecutionId and pipelineExecutionId.
 */
@Alpha
public interface RemoteStageMessage {

  /** The stage execution ID as generated by Orca. */
  String getStageExecutionId();

  /** The pipeline execution ID generated by Orca which the stage belongs to. */
  String getPipelineExecutionId();
}
